#!/bin/bash

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

print_status "Setting up custom functions..."

# Make all shell scripts in this directory executable (except init.sh)
for script in "$SCRIPT_DIR"/*.sh; do
    if [[ -f "$script" && "$(basename "$script")" != "init.sh" ]]; then
        chmod +x "$script"
        script_name=$(basename "$script")
        print_status "Made $script_name executable"
    fi
done

# Create aliases file for functions
ALIASES_FILE="$SCRIPT_DIR/../configs/shell/common/functions_aliases.sh"

print_status "Generating function aliases..."

# Start the aliases file
cat > "$ALIASES_FILE" << 'EOF'
#!/bin/bash
# Auto-generated aliases for custom functions
# This file is generated by functions/init.sh

EOF

# Generate aliases for all scripts (without .sh extension)
for script in "$SCRIPT_DIR"/*.sh; do
    if [[ -f "$script" && "$(basename "$script")" != "init.sh" ]]; then
        script_name=$(basename "$script" .sh)  # Remove .sh extension
        script_path="$script"
        
        echo "alias $script_name='$script_path'" >> "$ALIASES_FILE"
        print_status "Created alias: $script_name -> $script_path"
    fi
done

print_status "Functions setup completed!"
print_status "Generated aliases in: $ALIASES_FILE"
print_status "You can now run any script in this directory by name (without .sh)"
print_warning "Restart your terminal or source your shell config to apply changes"
